import type { Metadata } from "next";
import "./globals.css";
import Notification from "./components/common/notifications";
import { AuthProvider } from "@/context/authContext";
import SessionExpired from "./components/common/sessionExpired";

export const metadata: Metadata = {
  title: "FarmPady",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon-farmpady.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider>
          <Notification />
          <SessionExpired />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
